apiVersion: apps/v1
kind: Deployment #Service for service yml file
metadata:
  name: my-app
  labels: #selector key is used instead of lable - it connects to the deployment created with same lable value - for ex: nginx
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-image
          env:
            - name: SOME_ENV
              value: $SOME_ENV
          ports:
            - containerPort: 8080
