apiVersion: apps/v1
kind: Deployment #Service for service yml file
metadata:
  name: my-app
  labels: #/selectors incase of service file in order to apply service config to the created deployment
    app: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
        - name: my-app
          image: my-image
          env:
            - name: SOME_ENV
              value: $SOME_ENV
          ports:
            - containerPort: 8080
